[build]
  # Treat the `futebolasquartas` folder as the site base directory.
  # Netlify will run the `command` inside this folder and publish its output.
  base = "futebolasquartas"
  # No build command necessary for a plain static folder; keep the command empty
  # or set one if your folder requires a build step.
  command = ""
  # Publish the contents of the base directory (i.e. the folder itself)
  publish = "."
  # Functions live inside the same folder (the folder already contains delete-account.js)
  functions = "futebolasquartas"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
